/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void startButtonClicked(GButton source, GEvent event) { //_CODE_:button2:721551:
  bg = false;
  background(img);
  changeBackground();
  mic.start();
  song.start(); 
} //_CODE_:button2:721551:

public void songSelectionListClicked(GDropList source, GEvent event) { //_CODE_:Song_Selection:965194:
  mic = new Microphone(this);
  String choice = source.getSelectedText();
  if(choice == "Mary Had little Lamb") 
  song = new Song(this, "Little Lamb Melody.wav", "Little Lamb Melody.wav");
  
  if(choice == "You Belong With Me (Taylor Swift)") 
  song = new Song(this, "", "");
  
  if(choice == "Forever Like That (Ben Rector)") 
  song = new Song(this, "", "");
  
} //_CODE_:Song_Selection:965194:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  button2 = new GButton(this, 195, 190, 80, 30);
  button2.setText("Start");
  button2.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button2.addEventHandler(this, "startButtonClicked");
  Song_Selection = new GDropList(this, 123, 256, 221, 100, 4, 10);
  Song_Selection.setItems(loadStrings("list_965194"), 0);
  Song_Selection.addEventHandler(this, "songSelectionListClicked");
}

// Variable declarations 
// autogenerated do not edit
GButton button2; 
GDropList Song_Selection; 
